name: validation-linux
on: push

jobs:
  validate-linux:
    name: SPIR-V + GLSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get install spirv-tools glslang-tools graphviz
      - run: make validate-spv
      - run: make validate-glsl
      - run: make validate-dot
      - run: make validate-wgsl
